# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += widgets
TEMPLATE = app
TARGET = Store15_Re2DFA
DESTDIR = ./x64/Release
CONFIG += release
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
win32:RC_FILE = Store15_Re2DFA.rc
HEADERS += ./Re2DFA.h
SOURCES += ./Re2DFA.cpp \
    ./main.cpp
FORMS += ./Re2DFA.ui
RESOURCES += Re2DFA.qrc
